version: 2.1
jobs:
  setup:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - run:
          name: Download saucectl
          command: |
              SAUCECTL_VERSION=0.24.2
              SAUCECTL_BINARY=saucectl_${SAUCECTL_VERSION}_linux_64-bit.tar.gz
              curl -L -o ${SAUCECTL_BINARY} \
                -H "Accept: application/octet-stream" \
                https://github.com/saucelabs/saucectl/releases/download/v${SAUCECTL_VERSION}/${SAUCECTL_BINARY} \
                && tar -xvzf ${SAUCECTL_BINARY}
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  # Playwright Example
  test-playwright:
    working_directory: ~/app
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Playwright Tests
          command: |
            chmod -R 777 ./tests
            ./saucectl run -c ./.sauce/playwright.yml
          environment:
            SKIP_CI: true
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI


  # Testcafe Example
  test-testcafe:
    working_directory: ~/app
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Testcafe Tests
          command: |
            chmod -R 777 ./tests
            ./saucectl run -c ./.sauce/testcafe.yml
          environment:
            SKIP_CI: true
            BUILD_ID: $CIRCLE_BUILD_NUM
            BUILD_ENV: CircleCI

workflows:
  version: 2
  wb_workflow:
    jobs:
      - setup
      - test-testcafe:
          requires:
            - setup