version: 2.1
orbs:
  saucectl: saucelabs/saucectl-run@1.1.0
jobs:
  setup:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - run:
          name: Download saucectl
          command: |
            SAUCECTL_VERSION=0.24.2
            SAUCECTL_BINARY=saucectl_${SAUCECTL_VERSION}_linux_64-bit.tar.gz
            curl -L -o ${SAUCECTL_BINARY} \
              -H "Accept: application/octet-stream" \
              https://github.com/saucelabs/saucectl/releases/download/v${SAUCECTL_VERSION}/${SAUCECTL_BINARY} \
              && tar -xvzf ${SAUCECTL_BINARY}
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  test-testcafe-docker:
    docker:
      - image: cimg/base:stable
    environment:
      CI_COMMIT_SHORT_SHA: $CIRCLE_SHA1
      SAUCE_USERNAME: "oauth-sanslav-9907f"
      SAUCE_ACCESS_KEY: "02ddc349-b68e-4ae4-bcc7-48e2a40c34b5"
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - saucectl/saucectl-run:
          env: |
              SAUCE_USERNAME="oauth-sanslav-9907f"
              SAUCE_ACCESS_KEY="02ddc349-b68e-4ae4-bcc7-48e2a40c34b5"
          show-console-log: true

workflows:
  version: 2
  wb_workflow:
    jobs:
      - test-testcafe-docker
  everyhour:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - testcafe
    jobs:
      - test-testcafe-docker

