apiVersion: v1alpha
kind: testcafe

# Sauce Labs specific information
sauce:
  region: eu-central-1 # or us-west-1
  concurrency: 10 # Controls how many suites are executed at the same time.
  metadata:
    name: Default TestCafe with SauceCTL
    tags:
      - testcafe
      - default
    build: "TestCafe: Default test set - $DATE"

# Testcafe specific info
testcafe:
  version: 1.14.2
# Controls what files are available in the context of a test run (unless explicitly excluded by .sauceignore).
rootDir: ./

# Tests
suites:
  - name: "Testcafe - default - Chrome"
    browserName: chrome
    platformName: "Windows 10"
    screenResolution: "1600x1200"
    src:
      # test files glob
      - "**/*.js"

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    directory: ./artifacts
    match:
      - '*'
    when: always